// Array of Algerian wilayas
const wilayas = [
  {"code": "01", "name": "Adrar", "arabic_name": "أدرار"},
  {"code": "02", "name": "Chlef", "arabic_name": "الشلف"},
  {"code": "03", "name": "Laghouat", "arabic_name": "الأغواط"},
  {"code": "04", "name": "Oum El Bouaghi", "arabic_name": "أم البواقي"},
  {"code": "05", "name": "Batna", "arabic_name": "باتنة"},
  {"code": "06", "name": "Béjaïa", "arabic_name": "بجاية"},
  {"code": "07", "name": "Biskra", "arabic_name": "بسكرة"},
  {"code": "08", "name": "Béchar", "arabic_name": "بشار"},
  {"code": "09", "name": "Blida", "arabic_name": "البليدة"},
  {"code": "10", "name": "Bouïra", "arabic_name": "البويرة"},
  {"code": "11", "name": "Tamanrasset", "arabic_name": "تمنراست"},
  {"code": "12", "name": "Tébessa", "arabic_name": "تبسة"},
  {"code": "13", "name": "Tlemcen", "arabic_name": "تلمسان"},
  {"code": "14", "name": "Tiaret", "arabic_name": "تيارت"},
  {"code": "15", "name": "Tizi Ouzou", "arabic_name": "تيزي وزو"},
  {"code": "16", "name": "Algiers", "arabic_name": "الجزائر"},
  {"code": "17", "name": "Djelfa", "arabic_name": "الجلفة"},
  {"code": "18", "name": "Jijel", "arabic_name": "جيجل"},
  {"code": "19", "name": "Sétif", "arabic_name": "سطيف"},
  {"code": "20", "name": "Saïda", "arabic_name": "سعيدة"},
  {"code": "21", "name": "Skikda", "arabic_name": "سكيكدة"},
  {"code": "22", "name": "Sidi Bel Abbès", "arabic_name": "سيدي بلعباس"},
  {"code": "23", "name": "Annaba", "arabic_name": "عنابة"},
  {"code": "24", "name": "Guelma", "arabic_name": "قالمة"},
  {"code": "25", "name": "Constantine", "arabic_name": "قسنطينة"},
  {"code": "26", "name": "Médéa", "arabic_name": "المدية"},
  {"code": "27", "name": "Mostaganem", "arabic_name": "مستغانم"},
  {"code": "28", "name": "M'Sila", "arabic_name": "المسيلة"},
  {"code": "29", "name": "Mascara", "arabic_name": "معسكر"},
  {"code": "30", "name": "Ouargla", "arabic_name": "ورقلة"},
  {"code": "31", "name": "Oran", "arabic_name": "وهران"},
  {"code": "32", "name": "El Bayadh", "arabic_name": "البيض"},
  {"code": "33", "name": "Illizi", "arabic_name": "اليزي"},
  {"code": "34", "name": "Bordj Bou Arréridj", "arabic_name": "برج بوعريريج"},
  {"code": "35", "name": "Boumerdès", "arabic_name": "بومرداس"},
  {"code": "36", "name": "El Tarf", "arabic_name": "الطارف"},
  {"code": "37", "name": "Tindouf", "arabic_name": "تندوف"},
  {"code": "38", "name": "Tissemsilt", "arabic_name": "تسمسيلت"},
  {"code": "39", "name": "El Oued", "arabic_name": "الوادي"},
  {"code": "40", "name": "Khenchela", "arabic_name": "خنشلة"},
  {"code": "41", "name": "Souk Ahras", "arabic_name": "سوق أهراس"},
  {"code": "42", "name": "Tipaza", "arabic_name": "تيبازة"},
  {"code": "43", "name": "Mila", "arabic_name": "ميلة"},
  {"code": "44", "name": "Aïn Defla", "arabic_name": "عين الدفلى"},
  {"code": "45", "name": "Naâma", "arabic_name": "النعامة"},
  {"code": "46", "name": "Aïn Témouchent", "arabic_name": "عين تموشنت"},
  {"code": "47", "name": "Ghardaïa", "arabic_name": "غرداية"},
  {"code": "48", "name": "Relizane", "arabic_name": "غليزان"},
  {"code": "49", "name": "Timimoun", "arabic_name": "تيميمون"},
  {"code": "50", "name": "Bordj Badji Mokhtar", "arabic_name": "برج باجي مختار"},
  {"code": "51", "name": "Ouled Djellal", "arabic_name": "أولاد جلال"},
  {"code": "52", "name": "Béni Abbès", "arabic_name": "بني عباس"},
  {"code": "53", "name": "Ain Salah", "arabic_name": "عين صالح"},
  {"code": "54", "name": "Ain Guezzam", "arabic_name": "عين قزّام"},
  {"code": "55", "name": "Touggourt", "arabic_name": "تقرت"},
  {"code": "56", "name": "Djanet", "arabic_name": "جانت"},
  {"code": "57", "name": "El M'Ghair", "arabic_name": "المغير"},
  {"code": "58", "name": "El Menia", "arabic_name": "المنيعة"}
];

// Export the wilayas array
if (typeof module !== 'undefined' && module.exports) {
  module.exports = wilayas;
} 